#!/usr/bin/env bash

# CMDs
lastlogin="`last $USER | head -n1 | tr -s ' ' | cut -d' ' -f5,6,7`"
uptime="`uptime -p | sed -e 's/up //g'`"
host=`hostname`

# Options
hibernate=' Hiberner'
shutdown=' Éteindre'
reboot=" Redémarrer"
lock=' Vérrouiller'
suspend=' Suspendre'
logout=' Déconnecter'
yes=' Oui'
no=' Non'

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-mesg "<span> </span> Fonctionnement: $uptime" \
		-theme powermenu.rasi
}

# Confirmation CMD
confirm_cmd() {
	rofi -dmenu \
		-mesg 'Confirmer ?' \
		-theme powermenu.rasi
}

# Ask for confirmation
confirm_exit() {
	echo -e "$yes\n$no" | confirm_cmd
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$lock\n$logout\n$reboot\n$shutdown" | rofi_cmd
}

# Execute Command
run_cmd() {
	selected="$(confirm_exit)"
	if [[ "$selected" == "$yes" ]]; then
		if [[ $1 == '--shutdown' ]]; then
			systemctl poweroff
		elif [[ $1 == '--reboot' ]]; then
			systemctl reboot
        elif [[ $1 == '--lock' ]]; then
            if [[ -x '/usr/bin/betterlockscreen' ]]; then
                betterlockscreen -l
            elif [[ -x '/usr/bin/i3lock' ]]; then
                i3lock
            fi
		elif [[ $1 == '--logout' ]]; then
	        loginctl kill-session $XDG_SESSION_ID
		fi
	else
		exit 0
	fi
}

# Actions
chosen="$(run_rofi)"
echo $chosen
case ${chosen} in
    $shutdown)
        run_cmd --shutdown
        ;;
    $reboot)
		run_cmd --reboot
        ;;
    $lock)
		run_cmd --lock
        ;;
    $logout)
		run_cmd --logout
        ;;
esac
