#!/usr/bin/env bash
set -euo pipefail

default_layout="fr"
second_layout="us"
prefix="Clavier"

current_layout="$(setxkbmap -query | grep layout | awk '{print $2}')"

if [ "${current_layout}" == "${default_layout}" ]; then
    setxkbmap ${second_layout}
    dunstify "${prefix} ${second_layout}"
else
    setxkbmap ${default_layout}
    dunstify "${prefix} ${default_layout}"
fi
