# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5001664a-8766-4625-b3fc-2af084e42dff";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7451-E723";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d883cb6d-60d8-4c0a-9989-1c807cee25ee"; }
    ];

  fileSystems."/mnt/PERSO" =
    { device = "/dev/disk/by-uuid/b1b44759-b1a5-47c7-8019-d70d67099a1b";
      fsType = "ext4";
      options = [
        "defaults"
        "nofail"
      ];
    };

  fileSystems."/mnt/PRO" =
    { device = "/dev/disk/by-uuid/86aaa5e6-f8d3-4886-bf3e-c804c8559e6c";
      fsType = "ext4";
      options = [
        "defaults"
        "nofail"
        "noauto"
      ];
    };

  fileSystems."/mnt/GAMES" =
    { device = "/dev/disk/by-uuid/541e75e3-db7a-4367-a8d5-6d230e853faf";
      fsType = "ext4";
      options = [
        "defaults"
        "nofail"
      ];
    };

  fileSystems."/mnt/DATA" =
    { device = "/dev/disk/by-uuid/d7bbe9d8-4f98-4d87-b26a-34c75907f71a";
      fsType = "ext4";
      options = [
        "defaults"
        "nofail"
      ];
    };

  fileSystems."/mnt/VM" =
    { device = "/dev/disk/by-uuid/83e09479-85e0-45e1-82a3-217add68fe9e";
      fsType = "ext4";
      options = [
        "defaults"
        "nofail"
        "noauto"
      ];
    };

  fileSystems."/mnt/NEH" =
    { device = "/dev/disk/by-uuid/45b03bfe-40d7-45e4-8839-59792ca9fd9a";
      fsType = "ext4";
      options = [
        "nofail"
        "noauto"
      ];
    };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
